window_period: 1m
top_retweets: 10
oauth:
    :consumer_key: YMfCYzJUVVMJIgV5W4peGmGwb
    :consumer_secret: SHmcS8gyBcefsXkEEMh37csIYtz6KRKe9j0rMwDZXW5ZjSlcsH
    :token: 14226885-oONLk3tQzS9Dp7adPEDZhtj9iFITvsq0lB9Q6NS95
    :token_secret: VHZzuz7NMkmFijchtnaZ2vsZQfaGTK0NKkVwVeC1W6bDh
